Uber_new:
  0: index(BIGINT)
  1: fare_amount(FLOAT)
  2: pickup_datetime(DATETIME)
  3: pickup_longitude(FLOAT)
  4: pickup_latitude(FLOAT)
  5: dropoff_longitude(FLOAT)
  6: dropoff_latitude(FLOAT)
  7: passenger_count(BIGINT)
  8: trip_distance(FLOAT)
Weather_daily:
  0: index(BIGINT)
  1: DATE(DATETIME)
  2: DailyAverageWindSpeed(FLOAT)
Weather_hourly:
  0: index(BIGINT)
  1: DATE(DATETIME)
  2: LATITUDE(FLOAT)
  3: LONGITUDE(FLOAT)
  4: HourlyPrecipitation(TEXT)
  5: HourlyWindSpeed(FLOAT)
Yellow_Taxi:
  0: index(BIGINT)
  1: tpep_pickup_datetime(DATETIME)
  2: tpep_dropoff_datetime(DATETIME)
  3: passenger_count(BIGINT)
  4: trip_distance(FLOAT)
  5: pickup_longitude(FLOAT)
  6: pickup_latitude(FLOAT)
  7: dropoff_longitude(FLOAT)
  8: dropoff_latitude(FLOAT)
  9: fare_amount(FLOAT)
  10: tip_amount(FLOAT)